@url = http://localhost:5044
@id = 01994512-a5b5-723b-8994-55cad7c9ed49
GET {{url}}/api/city/

###
POST {{url}}/api/city/
Content-Type: application/json

{
  "name": "Tashkent"
}
###
DELETE {{url}}/api/city/{{id}}